FROM golang:1.22-alpine

RUN apk add --no-cache gcc musl-dev

RUN addgroup -S mercari && adduser -S trainee -G mercari
# RUN chown -R trainee:mercari /path/to/db

WORKDIR /tmp

COPY . /tmp/go
COPY db /tmp/db

RUN chown -R trainee:mercari /tmp/db

WORKDIR /tmp/go

RUN go mod tidy

RUN go build -o ./mercari-build-training ./app/*.go

CMD go run app/main.go
